fragment TaskFields on Task {
  id
  type
  name
  goal
  progress
  gemReward
  isCompleted
  proofType
  day
  createdAt
}

fragment MoneyFields on Money {
  currencyCode
  amount
}

fragment StaminaFields on Stamina {
  id
  current
  max
  isRegenerating
  regenRate
  regenIntervalSeconds
  nextRegenAt
  fullRegenAt
}

fragment DayStreakFields on DayStreak {
  id
  current
  max
  isExtendedToday
}

fragment ResponsePagingFields on ResponsePaging {
  totalRowCount
  totalPageCount
  currentPage
  currentPageSize
}

fragment LeaderboardUserFields on LeaderboardUser {
  id
  firstName
  lastName
  photoUrl
  score
  position
}

fragment ResponseQueryOptionsFields on ResponseQueryOptions {
  filters {
    field
    localization
    items {
      name
      localization
    }
  }
  sorts
}

fragment BalanceTransactionFields on BalanceTransaction {
  id
  amount {
    ...MoneyFields
  }
  type
  cause
  createdAt
}

fragment UserProfileFields on User {
  id
  username
  firstName
  lastName
  photoUrl
  roles
  locale {
    tag
    isManual
  }
  player {
    id
  }
}
